function [H0_dot, H0m_dot, Hm_dot ] = H_dot_Lagrange(Im,Bi0,P0,R0,pm,r0,t0,rL,tL,RL,robot)
%M_DOT_LAGRANGE Summary of this function goes here
%   Detailed explanation goes here

n = robot.n_links_joints;
n_q = robot.n_q;

[I_0d, I_Idot] = I_I_dot(R0,t0,RL,tL,robot);

% H0_dot = P0'*[I_0d          zeros(3);
%           zeros(3)      zeros(3)]*P0;
H0_dot = zeros(6);
H0m_dot = zeros(6, n_q);

Hm_dot = zeros(n_q);
for i = 1:n
    
    [J0i, Jmi] = Jacob(rL(1:3,i),r0,rL,P0,pm,i,robot);
    [J0i_dot, Jmi_dot] = Jacobdot(rL(1:3,i),tL(:,i),r0,t0,rL,tL,P0,pm,i,robot);
    mi = robot.links(i).mass;

    H0_dot  = H0_dot + J0i_dot'*[Im(:,:,i) zeros(3); ...
                                        zeros(3)  eye(3)*mi]*J0i...
                     + J0i'*[I_Idot(:,:,i) zeros(3); ...
                                    zeros(3)      zeros(3)]*J0i...
                     + J0i'*[Im(:,:,i) zeros(3); ...
                                    zeros(3)      eye(3)*mi]*J0i_dot;

    H0m_dot  = H0m_dot + J0i_dot'*[Im(:,:,i), zeros(3); ...
                                          zeros(3),  eye(3)*mi]*Jmi...
                               ...
                       + J0i'*[I_Idot(:,:,i), zeros(3); ...
                               zeros(3),      zeros(3)]*Jmi...
                               ...
                       + J0i'*[Im(:,:,i), zeros(3); ...
                                      zeros(3) ,    eye(3)*mi]*Jmi_dot;

    Hm_dot  = Hm_dot + Jmi_dot'*[Im(:,:,i) zeros(3); ...
                                 zeros(3)  eye(3)*mi]*Jmi...
                     + Jmi'*[I_Idot(:,:,i) zeros(3); ...
                             zeros(3)      zeros(3)]*Jmi...
                     + Jmi'*[Im(:,:,i) zeros(3); ...
                             zeros(3)      eye(3)*mi]*Jmi_dot;
end                  

% Hdot =[H0_dot   H0m_dot;
%        H0m_dot'  Hm_dot];
end

